src/assets/styles/settings/colors.pcss, src/assets/styles/settings/spacings.pcss, src/components/atoms/Activity/Activity.pcss, src/components/atoms/Calendar/Calendar.pcss, src/components/molecules/CarouselItem/CarouselItem.pcss, src/components/molecules/FaqItem/FaqItem.pcss, src/components/molecules/File/File.pcss, src/components/molecules/RegisterChild/RegisterChild.pcss, src/components/molecules/SocialsCta/SocialsCta.pcss, src/components/molecules/Tarif/Tarif.pcss, src/components/organisms/Carousel/Carousel.pcss, src/components/organisms/FAQ/FAQ.pcss, src/components/organisms/FileSection/FileSection.pcss, src/components/organisms/RegisterForm/Register.pcss, src/components/organisms/Tarifs/Tarifs.pcss
Every pcss that can be turned into a variable has been turned into a variable
=> css-variables

src/components/molecules/FaqItem/index.tsx, src/components/molecules/File/index.tsx, src/components/molecules/Paragraph/index.tsx, src/components/molecules/TableOfContents/index.tsx, src/components/molecules/Tarif/index.tsx, src/components/organisms/Policy/index.tsx, src/components/organisms/Tarifs/index.tsx
- Fixes to typography whitespace
=> Fix typography issues

.github/workflows/deploy.yml
=> Netlify GH workflow

src/components/organisms/RegisterForm/index.tsx, src/pages/api/register-user/index.tsx
- Add email step to register flow
- Add akabe boolean to email body
- Tweak copy
=> Register mails

globals.d.ts, package-lock.json, package.json, src/components/atoms/Image/Image.pcss, src/components/atoms/Image/index.tsx, src/components/atoms/Image/types.ts, src/components/molecules/FaqItem/index.tsx, src/components/molecules/Leader/index.tsx, src/components/organisms/Carousel/index.tsx, src/components/organisms/Gallery/index.tsx, src/components/organisms/TextImage/index.tsx
- Make images optionally maximisable (using `react-modal-image` package)
- Update dependencies
=> SLWEB-12 | Maximisable images

src/components/molecules/FooterHead/index.tsx
=> SLWEB-16 | Optional vat number

src/app/legal-info/page.tsx, src/components/organisms/Hero/types.ts, src/lib/helpers/metadata.ts
- Make some props optional
- Add `legal-info` page
=> SLWEB-17 | Hidden legal info page

src/app/(homepage)/query.ts, src/app/algemene-informatie/query.ts, src/app/contact/query.ts, src/app/drugs-en-alcohol/query.ts, src/app/inschrijven/query.ts, src/app/privacy-policy/query.ts, src/app/takken/[slug]/query.ts, src/app/takken/query.ts, src/app/verhuur/[slug]/query.ts, src/app/verhuur/query.ts, src/content-blocks/Divider/index.tsx, src/content-blocks/Divider/types.ts, src/content-blocks/FilesBlock/index.tsx, src/content-blocks/FilesBlock/types.ts, src/content-blocks/index.tsx, src/graphql/divider.gql
=> SLWEB-10 | Divider block

src/app/not-found.tsx, src/components/organisms/NotFound/NotFound.pcss, src/components/organisms/NotFound/index.tsx
=> SLWEB-18 | Error pages

src/components/atoms/BlockContainer/BlockContainer.pcss, src/components/atoms/BlockContainer/index.tsx
:sparkles: Feature
[SLWEB-20](https://scoutinglommel.atlassian.net/browse/SLWEB-20)
- Optimize block container variant modifiers
- Remove top padding from sibling light blocks
=> SLWEB-20 | Block container spacings

src/app/layout.tsx, src/app/query.ts, src/assets/styles/settings/colors.pcss, src/assets/styles/settings/elevation.pcss, src/components/atoms/Activity/index.tsx, src/components/atoms/GlobalAlert/GlobalAlert.pcss, src/components/atoms/GlobalAlert/index.tsx, src/components/atoms/GlobalAlert/types.ts, src/components/molecules/CarouselItem/CarouselItem.pcss
:sparkles: Feature
[SLWEB-31](https://scoutinglommel.atlassian.net/browse/SLWEB-21)
- Added global status banner
=> SLWEB-31 | Status banner

src/assets/styles/settings/colors.pcss, src/assets/styles/typography/title.pcss, src/components/atoms/BlockContainer/BlockContainer.pcss, src/components/atoms/Typography/Typography.pcss, src/components/organisms/Hero/Hero.pcss, src/components/organisms/YearThemeSection/YearThemeSection.pcss
:sparkles: Feature
[SLWEB-4](https://scoutinglommel.atlassian.net/browse/SLWEB-4)
- Make copy light on dark backgrounds
=> SLWEB-4 | Copy color

src/components/organisms/Forms/Register/index.tsx, src/lib/constants/emailAddress.ts
:bug: Bugfix
[SLWEB-32](https://scoutinglommel.atlassian.net/browse/SLWEB-32)
- Changed recipient for register form to `inschrijvingen@scoutinglommel.be`
=> SLWEB-32 | Register email recipient

src/components/molecules/CarouselItem/CarouselItem.pcss, src/components/organisms/FAQ/FAQ.pcss, src/components/organisms/Tarifs/index.tsx
:bug: Bugfix 
[SLWEB-35](https://scoutinglommel.atlassian.net/browse/SLWEB-35)
- Fix text color on carousel
- Add conditional for tarifs block cta button
- Align faq bottom text center
=> SLWEB-35 | Group names not visible

src/app/contact/page.tsx, src/components/organisms/Forms/Contact/ContactForm.tsx, src/components/organisms/Forms/Contact/index.tsx, src/components/organisms/Forms/Contact/types.ts
:sparkles: Feature
[SLWEB-36](https://scoutinglommel.atlassian.net/browse/SLWEB-36)
- Add the ability to pass the recipient via query params
- Extract the recipient from query params and use as initial values in contact form
=> SLWEB-36 | Contact recipients

src/components/organisms/Forms/FormBuilder/FormField/types.ts, src/components/organisms/Forms/Register/RegisterForm.tsx, src/lib/api/register/api.ts, src/lib/api/register/mutations.ts, src/lib/helpers/generateSitemap.ts
:sparkles: Feature 
[SLWEB-33](https://scoutinglommel.atlassian.net/browse/SLWEB-33)
- Add `comments` field to the register form
- Add hidden `workingYear` field to register form
- Fix `lastModified` field on sitemap
**Steps to reproduce:**
1. Go to [/inschrijven](http://localhost:3000/inschrijven)
=> SLWEB-33 | Register comments

src/lib/helpers/sendEmail.ts
:sparkles: Feature 
[SLWEB-44](https://scoutinglommel.atlassian.net/browse/SLWEB-44)
- Update and improve email layout
=> SLWEB-44 | Email layout

src/assets/styles/elements/hr.pcss, src/assets/styles/settings/colors.pcss, src/components/atoms/Activity/Activity.pcss, src/components/atoms/Divider/Divider.pcss, src/components/atoms/Divider/index.tsx, src/components/atoms/Divider/types.ts, src/components/atoms/Icon/IconMap.ts, src/components/molecules/FaqItem/FaqItem.pcss, src/components/molecules/FaqItem/FaqItem.stories.ts, src/components/molecules/FaqItem/index.tsx, src/components/molecules/FaqItem/types.ts, src/components/molecules/SocialsCta/SocialsCta.pcss, src/components/molecules/SocialsCta/index.tsx, src/components/molecules/Tarif/Tarif.pcss, src/components/organisms/FAQ/FAQ.pcss, src/components/organisms/FAQ/FAQ.stories.ts, src/components/organisms/FAQ/index.tsx, src/components/organisms/Forms/FormBuilder/FormField/index.tsx, src/components/organisms/Header/index.tsx, src/components/organisms/Hero/Hero.pcss, src/components/organisms/Tarifs/Tarifs.pcss, src/components/organisms/Tarifs/index.tsx, src/content-blocks/Divider/index.tsx
:bug: Bugfix
[SLWEB-1](https://scoutinglommel.atlassian.net/browse/SLWEB-1)
- Fix tarifs block
- Fix `<hr>` width / overflow
- Tweak social icons: stroke width + container height
- Fix font sizes
- Fix menu icon
- Tweak FAQ
- Fix hero cta
- Fix Turnstile theme
=> Fix | Visual fixes

src/assets/styles/elements/links.pcss, src/assets/styles/settings/colors.pcss, src/components/atoms/BlockContainer/BlockContainer.pcss, src/components/atoms/Button/Button.pcss, src/components/atoms/GlobalAlert/GlobalAlert.pcss
:bug: Bugfix
[SLWEB-47](https://scoutinglommel.atlassian.net/browse/SLWEB-47)
- Fix link colors
=> SLWEB-47 | Links on dark bg

locales/nl/common.json, src/components/molecules/FaqItem/FaqItem.pcss, src/components/molecules/YearTheme/types.ts, src/components/organisms/YearThemeSection/YearThemeSection.pcss, src/components/organisms/YearThemeSection/index.tsx
:sparkles: Feature / :bug: Bugfix
[SLWEB-48](https://scoutinglommel.atlassian.net/browse/SLWEB-48)
- Fix FAQ items on small screens
- Add year theme section button
=> SLWEB-48 | FAQ flex

locales/nl/forms.json, src/app/eetfestijn/page.tsx, src/components/organisms/Forms/Eetfestijn/Confirmation.tsx, src/components/organisms/Forms/Eetfestijn/EetfestijnForm.tsx, src/components/organisms/Forms/Eetfestijn/index.tsx, src/components/organisms/Forms/Eetfestijn/types.ts, src/components/organisms/Forms/FormBuilder/FormField/index.tsx, src/components/organisms/Forms/FormBuilder/FormField/types.ts, src/components/organisms/Forms/index.tsx, src/components/organisms/Forms/types.ts
:sparkles: Feature 
[SLWEB-41](https://scoutinglommel.atlassian.net/browse/SLWEB-41)
- Add eetfestijn page and form
=> SLWEB-41 | Google Sheets form submissions (WIP 🚧)

package-lock.json
=> Maintenance | Upgrade peer dependencies

locales/nl/common.json, src/app/takken/[slug]/page.tsx, src/components/atoms/Activity/index.tsx, src/components/organisms/Activities/index.tsx, src/components/organisms/Activities/types.ts, src/content-blocks/ActivitiesBlock/index.tsx, src/content-blocks/ActivitiesBlock/types.ts
:sparkles: Feature / :bug: Bugfix 
[SLWEB-59](https://scoutinglommel.atlassian.net/browse/SLWEB-59)
- Fetch activities async on the client to fix the issue where new and updated content is not coming through
=> SLWEB-59 | Async activities

src/app/handleidingen/[slug]/page.tsx, src/app/handleidingen/[slug]/query.ts
:bug: Bugfix
[SLWEB-55](https://scoutinglommel.atlassian.net/browse/SLWEB-55)
- Fix login guard for locked manuals
=> SLWEB-55 | Locked manuals bugfix

locales/nl/common.json, src/components/atoms/Typography/Typography.pcss, src/components/atoms/Typography/index.tsx, src/components/molecules/CarouselItem/CarouselItem.pcss, src/components/molecules/CarouselItem/index.tsx, src/components/molecules/FaqItem/FaqItem.pcss
:bug: Bugfix
[SLWEB-62](https://scoutinglommel.atlassian.net/browse/SLWEB-62)
- Fix text overlap
- Fix carousel item alignment
- Fix clamped typography
- Fix day map
=> SLWEB-62 | Activities fixes

package-lock.json, src/components/organisms/TextImage/TextImage.pcss
=> Bugfix | Text Image block img
